[package]
name = "graphics-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png", "gif", "bmp"] }
regex = "1.12.2"
show-image = "0.14"
stl_io = "0.10"
rand = "0.9.2"
